# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: vanilla_ubuntu
    displayName: stock Ubuntu with plain configure
    steps:
    - script: ./buildconf && ./configure
      displayName: 'Run configure'

    - script: make
      displayName: 'make'

    - script: make test-nonflaky
      displayName: 'test'

  - job: disable_ipv6
    displayName: without IPv6
    steps:
    - script: ./buildconf && ./configure --disable-ipv6
      displayName: 'Run configure --disable-ipv6'

    - script: make
      displayName: 'make'

    - script: make test-nonflaky
      displayName: 'test'
