extraction:
  cpp:
    prepare:
      packages: # to avoid confusion with libopenafs-dev which also provides a des.h
        - libssl-dev
    after_prepare: # make sure lgtm.com doesn't use CMake (which generates and runs tests)
      - rm -f CMakeLists.txt
      - ./buildconf
    configure: # enable as many optional features as possible
      command: ./configure --enable-ares --with-libssh2 --with-gssapi --with-librtmp --with-libmetalink --with-libmetalink
  python:
    python_setup:
      version: 3
    after_prepare:
      - python3 -m pip install --upgrade --user flake8
    before_index:
      - python3 -m flake8 --version  # flake8 3.6.0 on CPython 3.6.5 on Linux
      # stop the build if there are Python syntax errors or undefined names
      - python3 -m flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
      # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
      - python3 -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
