version: 7.50.0.{build}

platform:
  - x86
  - x64

configuration:
  - Release
  - Debug

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    TOOLCHAIN_VERSION: 15
    OPENSSL: OFF
    WINSSL: OFF
    TESTING: ON
    SHARED: OFF
    BUILD_TARGERT: windows_msvc

  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 14
    OPENSSL: OFF
    WINSSL: OFF
    TESTING: OFF
    SHARED: ON

  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 12
    OPENSSL: ON
    WINSSL: OFF
    TESTING: ON
    SHARED: OFF

  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 11
    OPENSSL: OFF
    WINSSL: ON
    TESTING: ON
    SHARED: OFF

  - BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 9
    OPENSSL: ON
    WINSSL: OFF
    TESTING: OFF
    SHARED: ON
    
  - BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 630
    OPENSSL: OFF
    WINSSL: ON
    TESTING: OFF
    SHARED: ON
    
  - BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 530
    OPENSSL: ON
    WINSSL: OFF
    TESTING: ON
    SHARED: OFF
    
install:
  - for /f "delims=" %%i in ('git describe --tags') do (set BUILD_VERSION=%%i)
  - if "%BUILD_VERSION%" == "" for /f "delims=" %%i in ('git rev-parse HEAD') do (set BUILD_VERSION=%%i) 
  - echo BUILD_VERSION=%BUILD_VERSION%
  
build_script:
    - if "%Configuration%"=="Debug" set ENABLE_DEBUG=ON
    - C:\msys64\usr\bin\bash.exe -e -l -c "bash /c/projects/curl/ci/build.sh /c/projects/curl"

test_script:
    #TODO: Temporarily disable testing
    #- if %TESTING%==ON (
    #    C:\msys64\usr\bin\bash.exe -e -l -c "cd /c/projects/curl/tests && ./runtests.pl -a -p !flaky !500 !1139" )

artifacts:
  - path: install
    name: libcurl_$(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(platform)_$(CONFIGURATION)_$(BUILD_VERSION)
    type: zip

# whitelist branches to avoid testing feature branches twice (as branch and as pull request)
branches:
    only:
        - master

deploy:
  provider: GitHub
  #token: https://github.com/settings/tokens encode token: https://ci.appveyor.com/tools/encrypt
  auth_token:
    secure:  #TODO: set your token
  on:
    appveyor_repo_tag: true        # deploy on tag push only
    SHARED: ON
