#***************************************************************************
#                                  _   _ ____  _
#  Project                     ___| | | |  _ \| |
#                             / __| | | | |_) | |
#                            | (__| |_| |  _ <| |___
#                             \___|\___/|_| \_\_____|
#
# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at https://curl.se/docs/copyright.html.
#
# You may opt to use, copy, modify, merge, publish, distribute and/or sell
# copies of the Software, and permit persons to whom the Software is
# furnished to do so, under the terms of the COPYING file.
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
# KIND, either express or implied.
#
# SPDX-License-Identifier: curl
#
###########################################################################

# https://ci.appveyor.com/project/curlorg/curl/history
# AppVeyor configuration:
#   https://www.appveyor.com/docs/appveyor-yml/
# AppVeyor worker images:
#   https://www.appveyor.com/docs/windows-images-software/

version: 7.50.0.{build}

environment:
  UNITY: 'ON'
  OPENSSL: 'OFF'
  DEBUG: 'ON'
  SHARED: 'OFF'
  matrix:
    # autotools-based builds (NOT mingw cross-compiling, but msys2 native)
    - job_name: 'autotools, msys2, Debug, x86_64, no Proxy, OpenSSL'
      APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      BUILD_SYSTEM: autotools
      TESTING: 'ON'
      DISABLED_TESTS: '!19 !1233'
      CONFIG_ARGS: '--enable-debug --enable-werror --disable-threaded-resolver --disable-proxy --with-openssl --enable-websockets --without-libpsl'
    - job_name: 'autotools, msys2, Debug, x86_64, OpenSSL'
      APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      BUILD_SYSTEM: autotools
      TESTING: 'ON'
      DISABLED_TESTS: '!19 !504 !704 !705 !1233'
      CONFIG_ARGS: '--enable-debug --enable-werror --disable-threaded-resolver --with-openssl --enable-websockets --without-libpsl'
    - job_name: 'autotools, msys2, Release, x86_64, OpenSSL'
      APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      BUILD_SYSTEM: autotools
      TESTING: 'ON'
      DISABLED_TESTS: '!19 !504 !704 !705 !1233'
      CONFIG_ARGS: '--enable-warnings --enable-werror --with-openssl --enable-websockets --without-libpsl'
    # autotools-based Cygwin build
    - job_name: 'autotools, cygwin, Debug, x86_64, OpenSSL'
      APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2022'
      BUILD_SYSTEM: autotools
      TESTING: 'ON'
      DISABLED_TESTS: ''
      ADD_SHELL: 'C:/cygwin64/bin'
      CONFIG_ARGS: '--enable-debug --enable-werror --disable-threaded-resolver --with-openssl --enable-websockets --without-libpsl'

install:
  - ps: |
      if($env:ADD_SHELL -ne $null) {
        $env:PATH = "$env:ADD_SHELL;$env:PATH"
        if($env:ADD_SHELL.Contains('cygwin')) {
          Start-ProcessWithOutput "setup-x86_64.exe -qgnNdO -l C:/cygwin64/var/cache/setup -R C:/cygwin64 -s https://cygwin.mirror.constant.com -P libssl-devel"
        }
      }
      else {
        $env:PATH = "C:/msys64/usr/bin;$env:PATH"
      }
      if($env:ADD_PATH -ne $null) {
        $env:PATH = "$env:ADD_PATH;$env:PATH"
      }

build_script:
  - cmd: sh -c ./appveyor.sh

clone_depth: 10

# select branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master
    - /\/ci$/

skip_commits:
  files:
    - '.azure-pipelines.yml'
    - '.circleci/*'
    - '.cirrus.yml'
    - '.github/**/*'
    - 'packages/**/*'
    - 'plan9/**/*'

artifacts:
  - path: '**/curl.exe'
    name: curl
  - path: '**/*curl*.dll'
    name: libcurl dll
