# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# SPDX-License-Identifier: curl

name: exports
on:
  push:
    branches:
    - master
    paths:
    - '**/exports-check.yml'
    - 'include/*.h'
    - 'libcurl.def'
  pull_request:
    branches:
    - master
    paths:
    - '**/exports-check.yml'
    - 'include/*.h'
    - 'libcurl.def'

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check libcurl.def exports
      run: |
        {
          echo 'EXPORTS'
          ./tests/extern-scan.pl | sort
        } | diff -u ./libcurl.def -
