# Copyright (C) Daniel Fandrich, <dan@coneharvesters.com>, et al.
#
# SPDX-License-Identifier: curl
#

name: Linux cmake

on:
  push:
    branches:
      - master
      - '*/ci'
    paths-ignore:
      - '**/*.md'
      - '.azure-pipelines.yml'
      - '.circleci/**'
      - '.cirrus.yml'
      - 'appveyor.*'
      - 'packages/**'
      - 'plan9/**'
      - 'projects/**'
      - 'winbuild/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '.azure-pipelines.yml'
      - '.circleci/**'
      - '.cirrus.yml'
      - 'appveyor.*'
      - 'packages/**'
      - 'plan9/**'
      - 'projects/**'
      - 'winbuild/**'

permissions: {}

env:
  MAKEFLAGS: -j 5
  DEBIAN_FRONTEND: noninteractive

jobs:
  cmake:
    name: linux (cmake)
    runs-on: 'ubuntu-latest'
    container: 'ubuntu:22.04'

    steps:
      - name: 'install prereqs'
        run: |
          sed -E -i -e s@[a-z]+\.debian\.org/@archive.debian.org/debian-archive/@ -e '/ stretch-updates /d' /etc/apt/sources.list
          apt-get update
          # See comment above if this fails after 2025-05-20
          apt-get install -y --no-install-suggests --no-install-recommends httrack
          httrack --get https://deb.freexian.com/extended-lts/pool/main/f/freexian-archive-keyring/freexian-archive-keyring_2022.06.08_all.deb
          dpkg -i freexian-archive-keyring_2022.06.08_all.deb
          echo 'deb http://deb.freexian.com/extended-lts stretch-lts main contrib non-free' | tee /etc/apt/sources.list.d/extended-lts.list
          apt-get update
          apt-get install -y --no-install-suggests --no-install-recommends cmake make gcc pkg-config libpsl-dev libzstd-dev zlib1g-dev libssl-dev libssh-dev libssh2-1-dev libc-ares-dev heimdal-dev libldap2-dev stunnel4 groff libgsasl-dev pkg-config

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: 'cmake generate (out-of-tree, c-ares, zstd, gssapi, libssh2, gsasl)'
        run: |
          mkdir bld-cares
          cd bld-cares
          cmake .. -DCMAKE_UNITY_BUILD=ON -DCURL_WERROR=ON -DBUILD_SHARED_LIBS=ON -DENABLE_ARES=ON -DCURL_ZSTD=ON -DCURL_USE_GSSAPI=ON -DCURL_USE_LIBSSH2=ON \
            -DUSE_LIBSSH=OFF -DCURL_USE_GSASL=ON

      - name: 'build'
        run: |
          make -C bld-cares
          bld-cares/src/curl --disable --version

      - name: 'install'
        run: make -C bld-cares install

      - name: 'tests'
        run: make -C bld-cares test-ci
