name: Linux

on:
  # Trigger the workflow on push or pull requests, but only for the
  # master branch
  push:
    branches:
    - master
    - '*/ci'
  pull_request:
    branches:
    - master

jobs:
  autotools:
    name: ${{ matrix.build.name }}
    runs-on: 'ubuntu-latest'
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        build:
        - name: NSS
          install:
          configure: --with-nss --enable-debug --enable-werror --with-nss-deprecated --enable-headers-api

    steps:
    - run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        . /etc/lsb-release
        sudo add-apt-repository -y "deb http://apt.llvm.org/${DISTRIB_CODENAME}/ llvm-toolchain-${DISTRIB_CODENAME}-14 main"
        sudo apt install -y clang-14 llvm-14
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 100
        sudo update-alternatives --set clang /usr/bin/clang-14
        sudo apt-get install libtool autoconf automake pkg-config stunnel4 libnss3-dev libpsl-dev libbrotli-dev libzstd-dev libnghttp2-dev nss-plugin-pem
        sudo python3 -m pip install impacket
      name: install prereqs and impacket

    - uses: actions/checkout@v2

    - run: autoreconf -fi
      name: 'autoreconf'

    - run: CC=clang CPPFLAGS="-isystem /usr/include/nss" ./configure ${{ matrix.build.configure }}
      name: 'configure with clang'

    - run: make V=1
      name: 'make'

    - run: make V=1 examples
      name: 'make examples'

    - run: make V=1 test-ci
      name: 'test'
      env:
        TFLAGS: "${{ matrix.build.tflags }}"
